### ISSUE TITLE
How can we set a controlled value?

### ISSUE THREAD

**Issue by tfmertz** [OMikkel/tailwind-datepicker-react#43]
For regular inputs you can turn it into a controlled input by adding a value prop so that you can change the input's value to whatever you'd like. Is that supported?

I don't really want to customize the input, just tell it what value I need when browsing through multiple different date items.

Is that possible?

Thanks!

**Comment by mark-barrett** [comment]
Opened PR for it: https://github.com/OMikkel/tailwind-datepicker-react/pull/44

**Comment by OMikkel** [comment]
Available in v1.4.3
