### ISSUE TITLE
minDate and maxDate dont prevent navigating across disabled dates.

### ISSUE THREAD

**Issue by parmeet1099** [OMikkel/tailwind-datepicker-react#51]
For eg. maxDate is set to 2nd Jan 2024. clicking on next() button, doesn't update the UI, i.e. the UI still shows Jan, 2024 calender but behind the hood, it navigates to furture months. so when i close and open it again it shows future disabled month, say something like May, 2024.             

<img width="400" alt="image" src="https://github.com/OMikkel/tailwind-datepicker-react/assets/123173970/b09fabcb-9ee6-41b0-9f6b-cee34b6d26a6">
<img width="400" alt="image" src="https://github.com/OMikkel/tailwind-datepicker-react/assets/123173970/fda2e6d5-bc6e-4d13-8bf2-878a3de406c1">
<img width="400" alt="image" src="https://github.com/OMikkel/tailwind-datepicker-react/assets/123173970/eaa1fe1e-9eea-4dbb-9b3d-9a8298568857">
<img width="400" alt="image" src="https://github.com/OMikkel/tailwind-datepicker-react/assets/123173970/df06a3c9-c454-47be-8e08-13834a691e7d">

**Comment by MrKeon** [comment]
I can confirm I have experienced this bug as well where clicking the Next/Prev button in the datepicker does not update the view, but when clicking outside of the datepicker, the date set correlates to the clicking of the Next/Prev button clicks

**Comment by pmaidens** [comment]
I have fixed this in #49. Hopefully it gets fixed soon.
